<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="3" hostname="DESKTOP-DJ4FDME" failures="9" tests="61" name="Test" time="85.794" errors="0" timestamp="2025-04-10T21:48:25 IST">
  <testcase classname="demoTestNG.TestScenario" name="fifth_testcase" time="0.01"/>
  <testcase classname="demoTestNG.TestScenario" name="first_testcase" time="0.014">
    <failure type="java.lang.AssertionError" message="expected [Hello1] but found [Hello]">
      <![CDATA[java.lang.AssertionError: expected [Hello1] but found [Hello]
at demoTestNG.TestScenario.first_testcase(TestScenario.java:15)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- first_testcase -->
  <testcase classname="demoTestNG.TestScenario" name="forth_testcase" time="0.004">
    <failure type="java.lang.AssertionError" message="expected [Hello1] but found [Hello]">
      <![CDATA[java.lang.AssertionError: expected [Hello1] but found [Hello]
at demoTestNG.TestScenario.forth_testcase(TestScenario.java:36)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- forth_testcase -->
  <testcase classname="demoTestNG.TestScenario" name="second_testcase" time="0.002"/>
  <testcase classname="demoTestNG.TestScenario" name="sixth_testcase" time="0.002"/>
  <testcase classname="demoTestNG.TestScenario" name="third_testcase" time="0.001"/>
  <testcase classname="demoTestNG.TestScenario10" name="fifth_testcase" time="0.003"/>
  <testcase classname="demoTestNG.TestScenario10" name="first_testcase" time="0.003"/>
  <testcase classname="demoTestNG.TestScenario10" name="forth_testcase" time="0.004"/>
  <testcase classname="demoTestNG.TestScenario10" name="second_testcase" time="0.004"/>
  <testcase classname="demoTestNG.TestScenario10" name="sixth_testcase" time="0.002"/>
  <testcase classname="demoTestNG.TestScenario10" name="third_testcase" time="0.003"/>
  <testcase classname="demoTestNG.TestScenario9" name="fifth_testcase" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [Hello1] but found [Hello]">
      <![CDATA[java.lang.AssertionError: expected [Hello1] but found [Hello]
at demoTestNG.TestScenario9.fifth_testcase(TestScenario9.java:38)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- fifth_testcase -->
  <testcase classname="demoTestNG.TestScenario9" name="first_testcase" time="0.002"/>
  <testcase classname="demoTestNG.TestScenario9" name="forth_testcase" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [Hello1] but found [Hello]">
      <![CDATA[java.lang.AssertionError: expected [Hello1] but found [Hello]
at demoTestNG.TestScenario9.forth_testcase(TestScenario9.java:31)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- forth_testcase -->
  <testcase classname="demoTestNG.TestScenario9" name="second_testcase" time="0.001"/>
  <testcase classname="demoTestNG.TestScenario9" name="sixth_testcase" time="0.002"/>
  <testcase classname="demoTestNG.TestScenario9" name="third_testcase" time="0.001"/>
  <testcase classname="demoTestNG.TestScenario8" name="fifth_testcase" time="0.003"/>
  <testcase classname="demoTestNG.TestScenario8" name="first_testcase" time="0.003"/>
  <testcase classname="demoTestNG.TestScenario8" name="forth_testcase" time="0.003"/>
  <testcase classname="demoTestNG.TestScenario8" name="second_testcase" time="0.011"/>
  <testcase classname="demoTestNG.TestScenario8" name="sixth_testcase" time="0.006"/>
  <testcase classname="demoTestNG.TestScenario8" name="third_testcase" time="0.003"/>
  <testcase classname="org.xyz.auto.fb.HandleKey_Mouse_Alerts_Window_Frames" name="tc01_handleFrames" time="71.235"/>
  <testcase classname="org.xyz.auto.fb.HandleKey_Mouse_Alerts_Window_Frames" name="tc02_handleAlerts" time="14.069"/>
  <testcase classname="demoTestNG.TestScenario3" name="fifth_testcase" time="0.003"/>
  <testcase classname="demoTestNG.TestScenario3" name="forth_testcase" time="0.001"/>
  <testcase classname="demoTestNG.TestScenario3" name="second_testcase" time="0.008"/>
  <testcase classname="demoTestNG.TestScenario3" name="sixth_testcase" time="0.002"/>
  <testcase classname="demoTestNG.TestScenario3" name="third_testcase" time="0.002"/>
  <testcase classname="demoTestNG.TestScenario2" name="sixth_testcase" time="0.004"/>
  <testcase classname="demoTestNG.TestScenario2" name="fifth_testcase" time="0.002"/>
  <testcase classname="demoTestNG.TestScenario2" name="forth_testcase" time="0.003"/>
  <testcase classname="demoTestNG.TestScenario2" name="third_testcase" time="0.002"/>
  <testcase classname="demoTestNG.TestScenario2" name="first_testcase" time="0.001"/>
  <testcase classname="demoTestNG.TestScenario2" name="second_testcase" time="0.005"/>
  <testcase classname="demoTestNG.TestScenario7" name="fifth_testcase" time="0.002"/>
  <testcase classname="demoTestNG.TestScenario7" name="first_testcase" time="0.001"/>
  <testcase classname="demoTestNG.TestScenario7" name="second_testcase" time="0.001"/>
  <testcase classname="demoTestNG.TestScenario7" name="sixth_testcase" time="0.006"/>
  <testcase classname="demoTestNG.TestScenario7" name="third_testcase" time="0.005">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at demoTestNG.TestScenario7.third_testcase(TestScenario7.java:25)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- third_testcase -->
  <testcase classname="demoTestNG.TestScenario7" name="forth_testcase" time="0.001">
    <skipped/>
  </testcase> <!-- forth_testcase -->
  <testcase classname="demoTestNG.TestScenario6" name="fifth_testcase" time="0.002"/>
  <testcase classname="demoTestNG.TestScenario6" name="first_testcase" time="0.003"/>
  <testcase classname="demoTestNG.TestScenario6" name="forth_testcase" time="0.003">
    <failure type="java.lang.AssertionError" message="expected [Hello1] but found [Hello]">
      <![CDATA[java.lang.AssertionError: expected [Hello1] but found [Hello]
at demoTestNG.TestScenario6.forth_testcase(TestScenario6.java:32)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- forth_testcase -->
  <testcase classname="demoTestNG.TestScenario6" name="second_testcase" time="0.003">
    <failure type="java.lang.AssertionError" message="expected [Hello1] but found [Hello]">
      <![CDATA[java.lang.AssertionError: expected [Hello1] but found [Hello]
at demoTestNG.TestScenario6.second_testcase(TestScenario6.java:19)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- second_testcase -->
  <testcase classname="demoTestNG.TestScenario6" name="sixth_testcase" time="0.002"/>
  <testcase classname="demoTestNG.TestScenario6" name="third_testcase" time="0.001"/>
  <testcase classname="demoTestNG.TestScenario5" name="fifth_testcase" time="0.001"/>
  <testcase classname="demoTestNG.TestScenario5" name="first_testcase" time="0.002"/>
  <testcase classname="demoTestNG.TestScenario5" name="forth_testcase" time="0.002"/>
  <testcase classname="demoTestNG.TestScenario5" name="second_testcase" time="0.001"/>
  <testcase classname="demoTestNG.TestScenario5" name="sixth_testcase" time="0.002"/>
  <testcase classname="demoTestNG.TestScenario5" name="third_testcase" time="0.002"/>
  <testcase classname="demoTestNG.TestScenario4" name="fifth_testcase" time="0.005"/>
  <testcase classname="demoTestNG.TestScenario4" name="first_testcase" time="0.001"/>
  <testcase classname="demoTestNG.TestScenario4" name="forth_testcase" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [Hello1] but found [Hello]">
      <![CDATA[java.lang.AssertionError: expected [Hello1] but found [Hello]
at demoTestNG.TestScenario4.forth_testcase(TestScenario4.java:32)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- forth_testcase -->
  <testcase classname="demoTestNG.TestScenario4" name="second_testcase" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [Hello1] but found [Hello]">
      <![CDATA[java.lang.AssertionError: expected [Hello1] but found [Hello]
at demoTestNG.TestScenario4.second_testcase(TestScenario4.java:19)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- second_testcase -->
  <testcase classname="demoTestNG.TestScenario4" name="sixth_testcase" time="0.001"/>
  <testcase classname="demoTestNG.TestScenario4" name="third_testcase" time="0.002"/>
  <testcase classname="org.xyz.auto.fb.HandleKey_Mouse_Alerts_Window_Frames" name="handlemouse" time="0.0">
    <ignored/>
  </testcase> <!-- handlemouse -->
  <testcase classname="demoTestNG.TestScenario3" name="first_testcase" time="0.0">
    <ignored/>
  </testcase> <!-- first_testcase -->
  <testcase classname="org.xyz.auto.fb.HandleKey_Mouse_Alerts_Window_Frames" name="handlekeyboard" time="0.0">
    <ignored/>
  </testcase> <!-- handlekeyboard -->
</testsuite> <!-- Test -->
